### ISSUE TITLE
Mainlining of uio_netx

### ISSUE THREAD

**Issue by simonschmeisser** [HilscherAutomation/nxdrvlinux#1]
Thanks for making the driver and libraries accessible here! :tada: 

Are there plans to merge the changes here into Linux mainline? https://github.com/torvalds/linux/blob/master/drivers/uio/uio_netx.c

We currently use a DKMS Debian package to replace the build in `uio_netx` with our internal fork but this causes trouble from time to time and simply using distribution kernel packages would be so much easier.

**Comment by MTrensch-hilscher** [comment]
Currently there are no plans to mainlining, as there are several changes (mapping DMA buffers into user space) which are usually not accepted.

**Comment by MTrensch-hilscher** [comment]
Currently nothing is planned

**Comment by wlfbck** [comment]
> We currently use a DKMS Debian package to replace the build in `uio_netx` with our internal fork but this causes trouble from time to time and simply using distribution kernel packages would be so much easier.

Hey, by chance we are running into the same issue (needing hilschers uio_netx in Debian). Could you share how exactly you did it and how your `dkms.conf` looks? We have some trouble with DKMS not replacing the uio_netx shipped with the Kernel.

**Comment by wlfbck** [comment]
Solved it ourself: The`uio_netx.c is missing a `MODULE_VERSION()` macro, adding that and then a standard dkms.conf is enough so that `"exactly matches what is already found in kernel"` no longer triggers and hilschers uio_netx is installed correctly.

@MTrensch-hilscher @sdoell-hilscher Is it possible to add that, possibly with `UIO_NETX_VERSION` as the value for it?

**Comment by simonschmeisser** [comment]
Sure. Unfortunately I'm currently on vacation so please send me a reminder in two weeks. I'll post here or add a PR then

Am Montag, 25. August 2025 schrieb Wolff Bock von Wülfingen:
> wlfbck left a comment (HilscherAutomation/nxdrvlinux#1)
> 
> > We currently use a DKMS Debian package to replace the build in `uio_netx` with our internal fork but this causes trouble from time to time and simply using distribution kernel packages would be so much easier.
> 
> Hey, by chance we are running into the same issue (needing hilschers uio_netx in Debian). Could you share how exactly you did it and how your `dkms.conf` looks? We have some trouble with DKMS not replacing the uio_netx shipped with the Kernel.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/HilscherAutomation/nxdrvlinux/issues/1#issuecomment-3219078368
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***

-- 
Gesendet von meinem Sailfish Handy

**Comment by MTrensch-hilscher** [comment]
@wlfbck Sorry, the issue just got lost (as it's closed) and as a possible answer was to be expected, nobody looked at it anymore.

I've found a little time to fiddle around with DKMS and tried it locally with the following dkms.conf, place in uio_netx directory, and no changes in the source code:
```
PACKAGE_NAME=uio_netx
PACKAGE_VERSION=3.0

DEST_MODULE_LOCATION=/kernel/drivers/uio
BUILT_MODULE_NAME=uio_netx

MAKE="'make' default modules_install KDIR=${kernel_source_dir}"
CLEAN="'make' clean"

AUTOINSTALL="yes"
```
and running the following commands:
```
sudo dkms add .
sudo dkms build uio_netx/3.0
sudo dkms install uio_netx/3.0
```

Afterwards modinfo just showed my version fine:
```
filename:       /lib/modules/6.8.0-85-generic/updates/dkms/uio_netx.ko.zst
description:    Device driver for netX hardware
		Hilscher Gesellschaft fuer Systemautomation mbH
author:         Hans J. Koch, Manuel Traut, Sebastian Doell
license:        GPL v2
srcversion:     D6649F39F36CCC38C953A02
alias:          pci:v000015CFd00004000sv00000000sd00000000bc*sc*i*
alias:          pci:v000015CFd00000020sv000015CFsd00000001bc*sc*i*
alias:          pci:v000015CFd00000020sv000015CFsd00000000bc*sc*i*
alias:          pci:v000015CFd00000010sv000015CFsd00000001bc*sc*i*
alias:          pci:v000015CFd00000010sv000015CFsd00000000bc*sc*i*
alias:          pci:v000010B5d00009030sv000010B5sd00003335bc*sc*i*
alias:          pci:v000010B5d00009030sv000010B5sd00003235bc*sc*i*
alias:          pci:v000015CFd00000000sv00000000sd00000000bc*sc*i*
depends:        uio
retpoline:      Y
name:           uio_netx
vermagic:       6.8.0-85-generic SMP preempt mod_unload modversions 
sig_id:         PKCS#7
signer:         ubuntu-2404-vbox Secure Boot Module Signature key
sig_key:        46:0B:0A:13:CF:E0:39:83:48:2A:FF:3E:0E:99:0F:B4:88:16:FF:8A
sig_hashalgo:   sha512
signature:      3F:0F:59:31:C3:64:0D:AD:45:60:A4:0C:4D:88:BB:06:A8:2A:53:5D:
		9E:EC:83:3E:85:25:E4:5E:AD:DA:14:1D:CA:07:73:B9:43:8B:19:CA:
		C6:EE:81:46:FA:CF:CC:22:10:07:A6:B4:20:4D:69:C9:BF:B9:A5:08:
		DD:8E:DB:3E:31:CB:FE:2E:B3:B1:13:CA:08:2D:F5:A6:76:72:F6:CF:
		61:B6:E9:C7:F5:B3:BA:BD:F9:71:F7:58:A2:FF:7A:6B:9B:9B:9E:A5:
		DC:95:F2:21:E4:64:50:89:5C:FF:3C:B4:36:7D:E9:F7:DB:AE:5A:25:
		3F:90:B9:92:EF:4A:58:55:F0:F3:68:E4:74:A1:61:E2:DF:6E:38:E4:
		42:EB:77:7B:4A:78:40:31:C5:DA:91:0B:89:46:D3:3F:83:4A:FC:8A:
		EF:0F:8D:D0:00:4A:35:33:33:47:E8:5C:8A:A1:47:DA:64:3D:07:E2:
		FE:0F:82:87:D6:FB:FE:09:AC:2D:CA:CD:76:D7:16:FB:7C:92:26:F7:
		96:E1:6C:8A:76:36:58:B8:6C:76:D4:99:F9:2C:34:15:BF:4B:62:C8:
		15:72:3D:9B:92:A2:96:8E:BB:5A:BC:04:C3:14:D9:72:0B:F9:82:38:
		8E:28:22:25:1A:01:9F:EB:5E:05:71:CD:1C:8D:F9:FA
parm:           custom_dpm_addr:Start address of DPM (array) (array of ullong)
parm:           custom_dpm_len:Length of DPM (array) (array of ulong)
parm:           custom_irq:IRQ number (array) (array of int)
parm:           ignore_pci_devices:Ignore PCI devices (int)
parm:           dma_disable:Disable DMA buffer allocation. (ulong)
parm:           dma_buffer_count:Number of DMA-buffers to use. (ulong)
parm:           dma_buffer_size:Size of a DMA-buffer. (ulong)
```

**Comment by wlfbck** [comment]
@MTrensch-hilscher No worries, your answer is much appreciated! :)
