### ISSUE TITLE
Troubleshooting CIFX 70E-CCIES Driver Installation on Ubuntu PC

### ISSUE THREAD

**Issue by MasakazuTobeta** [HilscherAutomation/nxdrvlinux#2]
Hello, I am currently performing initial operation verification by installing CIFX 70E-CCIES on an Ubuntu PC (x86_64). Although I haven't yet connected it to the CC-Link master, I have built and installed the driver, and executed the example. As a result, I obtained the following output:
https://github.com/TriOrb-Inc/nxdrvlinux/blob/dev/init_confirm/log/run_example.x86_64.log

It seems that the device is being detected around the lines below:
https://github.com/TriOrb-Inc/nxdrvlinux/blob/2fd731718bb797535c59f1d32687e7205ddc17d7/log/run_example.x86_64.log#L8

However, it appears to be failing to open around the lines below:
https://github.com/TriOrb-Inc/nxdrvlinux/blob/2fd731718bb797535c59f1d32687e7205ddc17d7/log/run_example.x86_64.log#L12
Is this indicative of a failed driver installation? Or would connecting it to the CC-Link master resolve the issue? Please advise. Thank you.

**Comment by MTrensch-hilscher** [comment]
I am not sure how you installed the driver but it seems that directory "/opt/cifx" does not contain the bootloader and required firmware binaries.

See 
![image](https://github.com/HilscherAutomation/nxdrvlinux/assets/26812655/3c6ea578-12ef-46a1-9596-db212f98f3f6)
 for directory layout
